apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-example
spec:
  replicas: 2
  selector:
    app: rc-app
  template:
    metadata:
      labels:
        app: rc-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80